### ISSUE TITLE
Richtext support

### ISSUE THREAD

**Issue by OmarWebDev** [Ali-Eldeba/functionalty.js#8]
Hello, Should we import richtext support? such as bold, italic, font-size etc In the library? The code is ready but should we merge it to the library?

Richtext like markdown

Author (Idea and code owner for richtext support): [@borma425](https://github.com/borma425/)

Examples:

https://user-images.githubusercontent.com/52567999/173658625-3816be58-9583-4051-ba4d-ebcffa6c4fde.mp4

https://user-images.githubusercontent.com/52567999/173658753-c445a115-99cc-45c1-a8a2-acb744a12335.mp4

**Comment by alieldeba** [comment]
I do not think that it will be a great idea

**Comment by OmarWebDev** [comment]
Me too I will close this issue.
